---

# We want one fact that tells us whether Google Chrome is installed or not
# This fact is
#  - app_installed = set True if we find Google Chrome in /Applications

- name: Gathering Google Chrome application status
  stat:
    path: "/Applications/Google Chrome.app"
  register: st

- debug:
    msg: "1 App state is {{ st.stat.exists }}"

- set_fact:
    app_installed: False

- debug:
    msg: "2 App installed is {{ app_installed }}"

- set_fact:
    app_installed: True
  when: st.stat.exists

- debug:
    msg: "3 App installed is {{ app_installed }}"
