---

- name: Check if Google Chrome application installed
  stat:
    path: "/Applications/Google Chrome.app"
  register: st

- set_fact:
    app_installed = bool (st.stat.exists)

#  - debug:
#      msg: "App state is {{ st.stat.exists }}"
#
#  - debug:
#      msg: "Inverted app state is {{ not st.stat.exists }}"
#
#  - debug:
#      msg: "Ext state is {{ (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions) }}"
#
#  - debug:
#      msg: "Inverted ext state is {{ not (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions) }}"
#
#  - set_fact:
#      role_state: "app_yes_ext_yes"
#      when: st.stat.exists and (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions)
#
#  - set_fact:
#      role_state: "app_no_ext_yes"
#      when: not st.stat.exists and (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions)
#
#  - set_fact:
#      role_state: "app_no_ext_no"
#      when: not st.stat.exists and not (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions)
#
#  - set_fact:
#      role_state: "app_yes_ext_no"
#      when: st.stat.exists and not (global_chrome_extensions or group_chrome_extensions or personal_chrome_extensions)
