---

# Role states:
#   - app = yes, ext =  no  -> Nothing to do, exit silently
#   - app =  no, ext =  no  -> Nothing to do, exit silently
#   - app = yes, ext = yes  -> Proceed with installing extensions
#   - app =  no, ext = yes  -> Print debug message, but don't fail the role unless role_strict is yes

# Check status of our three lists of extensions
# Sets ext_list
- include: check_ext.yml

# Check Google Chrome install status
# Sets app_installed
- include: check_app.yml
  when: ext_list

# If we have extension list(s), but Google Chrome is not installed,
# output a message and ext appropriately
- include: quit_messages.yml
  when: ext_list and not app_installed

# If everything is ok, actually install the extension preferences files
- include: install_ext.yml
  when: ext_list and app_installed
